"use client";
import {Fragment,useEffect,useState,useRef} from "react";
import {Scissors,Clock,ArrowRight,ArrowLeft,Check,CalendarDays,ShieldCheck,ChevronRight,ChevronUp,ChevronDown,MapPin,Phone} from "lucide-react";
import {Button} from "@/components/ui/button";
import {RadioGroup,RadioGroupItem} from "@/components/ui/radio-group";
import {Input} from "@/components/ui/input";
import {PhoneInput} from "@/components/phone-input";
import {normalizePhone,formatPhone} from "@/lib/phone";
import {today,time,price,hoursSummary,type SiteConfig} from "@/lib/booking";
function Instagram({size=24}:{size?:number}){
return <svg xmlns="http://www.w3.org/2000/svg" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"/><circle cx="12" cy="12" r="4"/><circle cx="18" cy="6" r="1" fill="currentColor" stroke="none"/></svg>;
}
function WhatsApp({size=24}:{size?:number}){
return <svg xmlns="http://www.w3.org/2000/svg" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M3 21l1.65-3.8a9 9 0 1 1 3.4 2.9L3 21"/><path d="M9 10a.5.5 0 0 0 1 0V9a.5.5 0 0 0-1 0v1a5 5 0 0 0 5 5h1a.5.5 0 0 0 0-1h-1a.5.5 0 0 0 0 1"/></svg>;
}
const MAP_URL="https://maps.app.goo.gl/57Cuf1TnEqRr7Qiw5";
const MAP_EMBED_URL="https://www.google.com/maps?q=-25.670698,-53.808721&z=17&output=embed";
const whatsappUrl=(number:string)=>"https://wa.me/"+number;
function TimeWheel({values,value,onChange}:{values:number[],value:number|null,onChange:(v:number)=>void}){
const rail=useRef<HTMLDivElement>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
const active=value===null?0:Math.max(0,values.indexOf(value));
useEffect(()=>{const index=value===null?0:Math.max(0,values.indexOf(value));if(rail.current)rail.current.scrollTop=index*56;if(value===null&&values.length)onChange(values[0]);return()=>{if(timer.current)clearTimeout(timer.current)}},[values]);
function choose(index:number){const i=Math.max(0,Math.min(values.length-1,index));if(timer.current)clearTimeout(timer.current);onChange(values[i]);rail.current?.scrollTo({top:i*56,behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"instant":"smooth"})}
return <div className="time-picker"><div className="wheel-label"><span>HORÁRIO</span><span>{values.length} disponíveis</span></div><div className="wheel-layout"><div className="wheel-frame"><div className="wheel-guide" aria-hidden="true"/><div ref={rail} className="wheel" role="listbox" aria-label="Horário do atendimento" aria-activedescendant={"slot-"+values[active]} tabIndex={0} onKeyDown={e=>{if(["ArrowUp","ArrowDown","Home","End"].includes(e.key)){e.preventDefault();choose(e.key==="Home"?0:e.key==="End"?values.length-1:active+(e.key==="ArrowDown"?1:-1))}}} onScroll={()=>{if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>{if(rail.current){const i=Math.max(0,Math.min(values.length-1,Math.round(rail.current.scrollTop/56)));onChange(values[i])}},100)}}>{values.map((t,i)=><div id={"slot-"+t} key={t} role="option" aria-selected={value===t} className={"wheel-option "+(value===t?"chosen":"")} onClick={()=>choose(i)}>{time(t)}</div>)}</div></div><div className="wheel-controls"><Button variant="outline" size="icon" onClick={()=>choose(active-1)} disabled={active===0} aria-label="Horário anterior"><ChevronUp/></Button><span>{value!==null&&value<720?"Manhã":"Tarde"}</span><Button variant="outline" size="icon" onClick={()=>choose(active+1)} disabled={active===values.length-1} aria-label="Próximo horário"><ChevronDown/></Button></div></div><p className="wheel-help">Role para escolher ou use as setas.</p></div>
}
export default function Home(){
const [service,setService]=useState("corte"),[step,setStep]=useState(0),[date,setDate]=useState(today()),[slot,setSlot]=useState<number|null>(null),[available,setAvailable]=useState<number[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[name,setName]=useState(""),[phone,setPhone]=useState(""),[saving,setSaving]=useState(false),[booking,setBooking]=useState<string|null>(null),[reload,setReload]=useState(0);
const [customerState,setCustomerState]=useState<"unknown"|"existing"|"new">("unknown");
const [site,setSite]=useState<SiteConfig|null>(null),[siteError,setSiteError]=useState(""),[blocked,setBlocked]=useState(false);
const panelRef=useRef<HTMLDivElement>(null);
useEffect(()=>{
 if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
 const animation=panelRef.current?.animate([{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],{duration:320,easing:'cubic-bezier(.22,1,.36,1)'});
 return()=>animation?.cancel();
},[step,booking]);
useEffect(()=>{fetch("/api/site",{cache:"no-store"}).then(async r=>{const d=await r.json() as SiteConfig&{error?:string};if(!r.ok)throw Error(d.error);setSite(d);setService(current=>d.services.some(s=>s.id===current)?current:d.services[0]?.id??"")}).catch(e=>setSiteError((e as Error).message||"Não foi possível carregar os dados da barbearia."))},[]);
const selected=site?.services.find(s=>s.id===service);
useEffect(()=>{if(!selected)return;const abort=new AbortController();setLoading(true);setSlot(null);setError("");fetch(`/api/bookings?date=${date}&service=${service}`,{signal:abort.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setAvailable(d.slots)}).catch(e=>{if(e.name!=="AbortError"){setError(e.message);setAvailable([])}}).finally(()=>{if(!abort.signal.aborted)setLoading(false)});return()=>abort.abort()},[date,service,reload,site]);
useEffect(()=>{const context=(document as any).modelContext;if(!site||!context?.registerTool)return;const life=new AbortController();Promise.resolve(context.registerTool({name:"select_booking_service",description:"Seleciona o serviço no formulário, sem criar uma reserva.",inputSchema:{type:"object",properties:{service:{type:"string",enum:site.services.map(s=>s.id)}},required:["service"],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!site.services.some(s=>s.id===input.service))throw Error("Serviço inválido");setService(input.service);setStep(0);return {selectedService:input.service}}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[site]);
async function submit(e:React.FormEvent){
 e.preventDefault();if(saving)return;setError("");setBlocked(false);
 if(!normalizePhone(phone)){setError("Informe um telefone brasileiro válido com DDD.");return;}
 setSaving(true);
 try{
  if(customerState==="unknown"){
   const r=await fetch("/api/customers/lookup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({phone})});
   const d=await r.json();if(!r.ok){if(d.code==="PHONE_BLOCKED")setBlocked(true);throw Error(d.error)}
   setCustomerState(d.registered?"existing":"new");return;
  }
  const r=await fetch("/api/bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({service,date,start:slot,...(customerState==="new"?{name}:{}),phone})});
  const d=await r.json();if(!r.ok){if(d.code==="NAME_REQUIRED")setCustomerState("new");if(d.code==="PHONE_BLOCKED")setBlocked(true);if(r.status===409){setStep(1);setReload(x=>x+1)}throw Error(d.error)}setBooking(d.id);
 }catch(e){setError((e as Error).message)}finally{setSaving(false)}
}
const prettyDate=new Date(date+"T12:00:00").toLocaleDateString("pt-BR",{day:"numeric",month:"long"});
return <div className="site"><header className="header"><a href="/" className="brand"><img src="/logo.png" alt="Barbearia Sharp Razors"/><span>SHARP RAZORS<small>BARBEARIA</small></span></a><nav><a className="active" href="#agendamento">Agendamento</a><a href="#horarios">Horários</a><a className="nav-location" href="#localizacao">Localização</a>{site?.whatsapp&&<a href={whatsappUrl(site.whatsapp)} target="_blank" rel="noreferrer" aria-label="WhatsApp da barbearia"><WhatsApp size={19}/></a>}<a href="https://www.instagram.com/barbeariasharprazors/" target="_blank" rel="noreferrer" aria-label="Instagram da barbearia"><Instagram size={19}/></a></nav></header>
<main><div className="intro"><p className="eyebrow">BARBEARIA SHARP RAZORS</p><h1>MARQUE SEU HORÁRIO<span>.</span></h1></div>
<div className="workspace" id="agendamento"><section className="booking-panel"><div className="steps">{["Serviço","Data e horário","Seus dados"].map((s,i)=><button key={s} disabled={i>step||!!booking||saving} onClick={()=>setStep(i)} className={i===step?"current":i<step?"done":""}><span>{i<step?<Check size={15}/>:"0"+(i+1)}</span>{s}{i<2&&<ChevronRight className="step-chevron" size={15}/>}</button>)}</div>
{booking?<div ref={panelRef} className="success"><div className="success-icon"><Check size={34}/></div><p className="eyebrow">TUDO CERTO</p><h2>Horário reservado!</h2><p>Seu agendamento está registrado.</p><div className="receipt"><strong>{selected?.name}</strong><span>{prettyDate} às {time(slot!)}</span><span>Equipe Sharp Razors · {selected?.duration} min</span><small>Comprovante: {booking.slice(0,8).toUpperCase()}</small></div><p className="fine">Guarde este comprovante. Para alterações, entre em contato com a barbearia pelo WhatsApp ou Instagram.</p><Button className="primary" onClick={()=>{setBooking(null);setStep(0);setName("");setPhone("");setCustomerState("unknown");setReload(x=>x+1)}}>Fazer outro agendamento <ArrowRight/></Button></div>:<div ref={panelRef} className="panel-body">
<div className="section-heading"><p className="eyebrow">ETAPA 0{step+1} DE 03</p><h2>{["O que vai ser hoje?","Escolha o seu horário.","Para fechar o agendamento."][step]}</h2><p>{["Escolha o serviço para o seu próximo atendimento.","Escolha uma data e um dos horários disponíveis.","Informe seu telefone para consultar o cadastro."][step]}</p></div>
{step===0&&(site?<><RadioGroup value={service} onValueChange={setService} className={"service-list"+(site.services.length>4?" is-scrollable":"")} aria-label="Serviço">{site.services.map((s,i)=><label key={s.id} className={"service-card "+(service===s.id?"selected":"")} htmlFor={"service-"+s.id}><span className="service-number">{String(i+1).padStart(2,"0")}</span><div className="service-copy"><h3>{s.name}</h3><span className="duration"><Clock size={13}/>{s.duration} min <b>·</b> {price(s.priceCents)}</span></div><RadioGroupItem value={s.id} id={"service-"+s.id}/></label>)}</RadioGroup><div className="quiet-note"><ShieldCheck size={17}/> O valor do serviço é confirmado com a barbearia.</div></>:<p className="loading-note" role={siteError?"alert":undefined}>{siteError||"Carregando serviços…"}</p>)}
{step===1&&<div className="date-selection"><label htmlFor="date">Data do atendimento</label><Input id="date" type="date" min={today()} max={new Date(Date.now()+89*86400000).toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/><div className="availability" aria-live="polite">{loading?<p>Consultando horários…</p>:available.length===0?<div className="empty"><CalendarDays/><p>Nenhum horário disponível nesta data.</p><span>Selecione outro dia para continuar.</span></div>:<TimeWheel values={available} value={slot} onChange={setSlot}/>}</div><p className="fine">Horários de Brasília. Agendamentos com até 90 dias de antecedência.</p></div>}
{step===2&&<form id="booking-form" onSubmit={submit} className="details-form">
<label htmlFor="phone">Telefone com DDD</label>
<PhoneInput id="phone" describedBy="phone-help" disabled={saving} value={phone} onChange={value=>{setPhone(value);setCustomerState("unknown");setName("");setError("");setBlocked(false)}}/>
<p id="phone-help" className="phone-help">Use o mesmo número nos próximos agendamentos.</p>
<div aria-live="polite">
{customerState==="existing"&&<div className="customer-found"><Check size={20}/><div><strong>Telefone já cadastrado.</strong><p>Confira o horário abaixo e confirme sua reserva.</p></div></div>}
{customerState==="new"&&<div className="new-customer"><p>Primeira vez com este telefone? Informe seu nome para o cadastro.</p><label htmlFor="name">Nome completo</label><Input id="name" autoComplete="name" placeholder="Seu nome completo" required minLength={3} maxLength={100} disabled={saving} value={name} onChange={e=>setName(e.target.value)}/></div>}
</div>
{customerState!=="unknown"&&<div className="confirmation-summary"><span>SEU AGENDAMENTO</span><strong>{selected?.name}</strong><p>{prettyDate} às {slot===null?"—":time(slot)} · {selected?.duration} min</p></div>}
<div className="contact-note"><ShieldCheck size={21}/><p>Seus dados serão usados pela barbearia para identificar e atender seu agendamento.</p></div>
</form>}

{error&&step>0&&<div className="error" role="alert">{error}{step===1&&<button onClick={()=>setReload(x=>x+1)}>Tentar novamente</button>}{blocked&&site?.whatsapp&&<a className="error-whatsapp" href={whatsappUrl(site.whatsapp)+"?text="+encodeURIComponent("Olá! Tentei agendar um horário pelo site e não consegui. Podem me ajudar?")} target="_blank" rel="noreferrer"><WhatsApp size={17}/>Falar no WhatsApp · {formatPhone(site.whatsapp)}<ArrowRight size={15}/></a>}</div>}
<div className="panel-footer"><span>{step===0?(site?.services.some(s=>s.priceCents===null)?"Preços sob consulta":"Valores por serviço"):<button className="back" disabled={saving} onClick={()=>setStep(step-1)}><ArrowLeft size={16}/> Voltar</button>}</span>{step<2?<Button className="primary" disabled={(step===0&&!selected)||(step===1&&(slot===null||loading))} onClick={()=>setStep(step+1)}>Continuar <ArrowRight size={18}/></Button>:<Button form="booking-form" type="submit" className="primary" disabled={saving}>{saving?(customerState==="unknown"?"Consultando…":"Reservando…"):(customerState==="unknown"?"Continuar com telefone":"Confirmar agendamento")}<Check size={18}/></Button>}</div>
</div>}</section>
<aside><section className="brand-card"><img src="/logo.png" alt="Logo Sharp Razors"/><p className="eyebrow">BARBEARIA</p><h2>NA RÉGUA.<br/>NO SEU TEMPO.</h2><div className="brand-divider"/><div className="appointment-summary"><span>SEU AGENDAMENTO</span>{selected&&<><div><Scissors size={17}/><strong>{selected.name}</strong></div><div><Clock size={17}/>{selected.duration} minutos · Equipe Sharp Razors</div></>}{slot!==null&&<div><CalendarDays size={17}/>{prettyDate}, {time(slot)}</div>}</div></section>
<section className="hours" id="horarios"><h3><Clock size={18}/> Horário de funcionamento</h3>{site?<dl>{hoursSummary(site.hours).map(g=><Fragment key={g.label}><dt>{g.label}</dt>{g.closed?<dd className="closed">Fechado</dd>:<dd>{time(g.periods[0][0])} – {time(g.periods[0][1])}{g.periods.slice(1).map(p=><span key={p[0]}>{time(p[0])} – {time(p[1])}</span>)}</dd>}</Fragment>)}</dl>:<p className="loading-note">{siteError||"Carregando horários…"}</p>}<a href="https://www.instagram.com/barbeariasharprazors/" target="_blank" rel="noreferrer"><Instagram size={17}/>@barbeariasharprazors <ArrowRight size={15}/></a>{site?.whatsapp&&<a href={whatsappUrl(site.whatsapp)} target="_blank" rel="noreferrer"><WhatsApp size={17}/>{formatPhone(site.whatsapp)} <ArrowRight size={15}/></a>}{site?.phone&&site.phone!==site.whatsapp&&<a href={"tel:+"+site.phone}><Phone size={17}/>{formatPhone(site.phone)} <ArrowRight size={15}/></a>}</section></aside></div>
<section className="location" id="localizacao"><div className="location-info"><p className="eyebrow">ONDE ESTAMOS</p><h2>VENHA NOS VISITAR<span>.</span></h2><p>Estamos te esperando na Barbearia Sharp Razors. Use o mapa para traçar sua rota.</p><a className="location-link" href={MAP_URL} target="_blank" rel="noreferrer"><MapPin size={17}/>Abrir no Google Maps <ArrowRight size={15}/></a>{site?.whatsapp&&<a className="location-link" href={whatsappUrl(site.whatsapp)} target="_blank" rel="noreferrer"><WhatsApp size={17}/>Falar no WhatsApp <ArrowRight size={15}/></a>}</div><div className="location-map"><iframe title="Mapa com a localização da Barbearia Sharp Razors" src={MAP_EMBED_URL} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/></div></section></main>
<footer><span>© {new Date().getFullYear()} Sharp Razors</span><span>Corte · Barba · Sharp Razors</span><span>BARBEARIA & ESTILO</span></footer></div>}
